### ISSUE TITLE
Two issues with "Apply Identical Effects" setting

### ISSUE THREAD

**Issue by krbz999** [GamerFlix/effective-transferral#32] opened 2022-09-04 23:48 UTC
- When the setting is enabled, you cannot apply Active Effects to linked actors (target or self), triggering a Foundry warning about a faulty `_id`.
- When the setting is enabled, reverting the applied Warp Gate mutation does not remove the Active Effects from the actor.

![image](https://user-images.githubusercontent.com/50169243/188338289-7d94542f-c1dd-4c8a-b58d-520316d31ebe.png)

**Comment by GamerFlix** [comment] 2022-09-12 20:19
Completely missed that during the initial tests. I might need to resort to adding a custom flag with a random id to use as a comparison value instead.

**Comment by GamerFlix** [comment] 2022-09-12 20:51
Change failed to fix the failure of reverting the mutation. Will have to give this a closer look.

**Comment by krbz999** [comment] 2022-09-12 21:14
I am able to reproduce the issue using just Warp Gate, so it does not seem to be ET. Seems like WG cannot retrieve the id it creates itself.

**Comment by GamerFlix** [comment] 2022-12-02 19:20
Two potential ways:
Update the mutation stack to have the correct id aka: https://gist.github.com/trioderegion/34fc727e22cfd46b9fb89fb59bee7b1b#file-powermorph-phase3-js-L90
Put my own comparison key in a flag and use that.

Presently leaning towards the second

**Comment by GamerFlix** [comment] 2022-12-02 19:50
Trying to go with solution 2 ran into upstream issues as detailed here: https://github.com/trioderegion/warpgate/issues/102

Unrelatedly warpgate's handling of ids as comparison keys should be improved in the future here: https://github.com/trioderegion/warpgate/issues/103

**Comment by trioderegion** [comment] 2022-12-06 23:40
https://github.com/trioderegion/warpgate/issues/102 and https://github.com/trioderegion/warpgate/issues/103 are resolved in Warp Gate v1.15.3 and should restore expected operation.

**Comment by krbz999** [comment] 2022-12-08 14:37
Testing reveals that the 'Apply identical effects' setting still does not work, returning a model validation error regarding invalid ids when enabled.

**Comment by GamerFlix** [comment] 2022-12-08 17:46
> Testing reveals that the 'Apply identical effects' setting still does not work, returning a model validation error regarding invalid ids when enabled.

That's arguably worse than on warpgate 1.15.2 where it simply failed to revert but did not block application.

**Comment by krbz999** [comment] 2022-12-08 17:57
Maybe stripping the ID entirely and putting your own `foundry.utils.random()` into an ET flag when the setting is enabled and using that as comparison key could be a solution?

**Comment by GamerFlix** [comment] 2022-12-08 18:11
> Maybe stripping the ID entirely and putting your own `foundry.utils.randomID()` into an ET flag when the setting is enabled and using that as comparison key could be a solution?

That was previously done but lead to upstream issues detailed in one of the issues linked above. Changing it back to that workaround and seeing whether this now works is certainly a way forward that will be investigated.

**Comment by trioderegion** [comment] 2022-12-08 18:57
The tangled web we weave....

Creation by `id` or `_id` *should* work, however, it is currently the user's responsibility to provide a unique ID if its a creation operation -- otherwise it *should* be treated as an update.

Note the use of "should". I'll keep digging in on my side and see if I can provide helper functions/flags/something to allow a use to say "ensure this identifier I passed is unique and modify if not."

**Comment by GamerFlix** [comment] 2022-12-08 19:40
> The tangled web we weave....
> 
> Creation by `id` or `_id` *should* work, however, it is currently the user's responsibility to provide a unique ID if its a creation operation -- otherwise it *should* be treated as an update.
> 
> Note the use of "should". I'll keep digging in on my side and see if I can provide helper functions/flags/something to allow a user to say "ensure this identifier I passed is unique and modify if not."
> 
> This may be tangential to the specific bug/issue being discussed here, but i know we have all shifted around a few times to work around issues.

Ahhh and since the effect's data cokes from an existent effect the second application fails. So replacing the id in the data with randomId() should technically work. Sadly don't have the time to test whether this fixes the issue right now but that's a good way forward.

**Comment by GamerFlix** [comment] 2022-12-09 00:05
> Creation by `id` or `_id` _should_ work, however, it is currently the user's responsibility to provide a unique ID if its a creation operation -- otherwise it _should_ be treated as an update.

I tested this and set the _id field in the effect to an id generated by foundry.utils.randomId() which should satisfy Foundry's id requirements. Mutating the actor using said effect data and a comparison key of id resulted in a datamodel validation error however telling my the _id has to be an alphanumeric [...] string.
My adjustment of the effect data is also unlikely to be at fault as even using undmodified data from an existing working effect causes the same issue when used in a warpgate mutation. This was not the case in warpgate 1.15.2. As such I think it is fair to say that https://github.com/trioderegion/warpgate/issues/103 has not been resolved correctly and the implemented "solution" that was intended to do this arguably broke it further.

**Closed** 2022-12-09 01:49 UTC
Labels: bug, upstream
